sudo: required
dist: trusty
language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
env:
  # Setting this variable twice will cause the 'script' section to run twice with the respective env var invoked
  - BUILD_TYPE=test
script:
  - src/bin/travis/travisRepeat.sh
